modLoader = "javafml"
loaderVersion = "[1,)"

logoFile = "icon.png"
authors = "90"
license = "LGPLv3.0"

issueTrackerURL = "https://github.com/62832/AppliedE/issues"
displayURL = "https://github.com/62832/AppliedE"
updateJSONURL = "https://mod-manifest.jarva.dev/manifest/curseforge/1009940/neoforge"

[[mods]]
modId = "appliede"
version = "$version"
displayName = "AppliedE"
description = "Direct EMC integration with Applied Energistics 2."

[[mixins]]
config = "appliede.mixins.json"

[[dependencies.appliede]]
modId = "ae2"
versionRange = "[19.2.9,)"

[[dependencies.appliede]]
modId = "projecte"
versionRange = "[1.0.1,)"

[[dependencies.appliede]]
modId = "ae2wtlib"
type = "optional"
versionRange = "[19,)"

[[dependencies.appliede]]
modId = "teamprojecte"
type = "optional"
versionRange = "[1.1.3,)"
side = "SERVER"
