name: Build

on:
  pull_request:
    # Only on branches, not tags/releases
    branches: ["**"]
  push:
    branches: ["*"]
  release:
    types: [published]

permissions:
  contents: write

concurrency:
  group: ci-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build release files
        run: ./gradlew build
      - name: Publish release files
        if: ${{ github.event_name == 'release' }}
        uses: Kir-Antipov/mc-publish@c0f30ad683340ba9a5374ba42157179f30171107
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

          curseforge-id: 1009940
          curseforge-token: ${{ secrets.CURSEFORGE_API_KEY }}

          modrinth-id: SyKS54UY
          modrinth-token: ${{ secrets.MODRINTH_API_KEY }}

          game-versions: 1.21.1
          loaders: neoforge
          dependencies: |
            ae2(required){curseforge:223794}{modrinth:XxWD5pD3}
            projecte(required){curseforge:226410}
            ae2wtlib(optional){curseforge:459929}{modrinth:pNabrMMw}
            teamprojecte(optional){curseforge:689273}
